#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 06, 2024 10:28:50 AM CEST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import pianoKeyboard

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top2, _w2
    _top2 = root
    _w2 = pianoKeyboard.Toplevel2(_top2)
    root.mainloop()

def send_start(*args):
    if _debug:
        print('pianoKeyboard_support.send_start')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def send_stop(*args):
    if _debug:
        print('pianoKeyboard_support.send_stop')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    pianoKeyboard.start_up()




